-- Generated by drizzle-kit, then hand-edited so it applies cleanly to databases
-- that ALREADY contain rows: new NOT NULL columns are added nullable, backfilled,
-- and only then constrained. The resulting schema is identical to the snapshot.
CREATE TYPE "public"."task_priority" AS ENUM('none', 'low', 'medium', 'high', 'urgent');--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "avatar_url" text;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "priority" "task_priority" DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE "workspaces" ADD COLUMN "key" varchar(10);--> statement-breakpoint
UPDATE "workspaces"
SET "key" = COALESCE(NULLIF(upper(left(regexp_replace("name", '[^A-Za-z]', '', 'g'), 3)), ''), 'MTX');--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "key" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "workspaces" ADD COLUMN "task_seq" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "number" integer;--> statement-breakpoint
WITH numbered AS (
  SELECT t."id",
         row_number() OVER (PARTITION BY b."workspace_id" ORDER BY t."created_at", t."id") AS rn
  FROM "tasks" t
  JOIN "boards" b ON b."id" = t."board_id"
)
UPDATE "tasks" SET "number" = numbered.rn FROM numbered WHERE "tasks"."id" = numbered."id";--> statement-breakpoint
UPDATE "workspaces" w
SET "task_seq" = COALESCE((
  SELECT max(t."number") FROM "tasks" t JOIN "boards" b ON b."id" = t."board_id" WHERE b."workspace_id" = w."id"
), 0);--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "number" SET NOT NULL;
